language: go
sudo: required

go:
  - "1.15"

services:
  - docker
  - postgresql
  - redis

before_script:
  - psql -c "CREATE DATABASE forest;" -U postgres
  - psql -c "CREATE USER vicanso WITH PASSWORD 'A123456';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE forest to vicanso;" -U postgres

script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin latest
  - make lint
  - make test

after_success:
  - docker build -t forest .
  - docker tag forest $DOCKER_USERNAME/forest:latest
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/forest:latest
  - docker images
