app: forest
requestLimit: 1024
# apiPrefix: /api
listen: ":7001"

# cookie track key
track: jt


# redis 配置(pass从env中获取pass这个配置为密码，如果未配置则为空)
redis: redis://127.0.0.1:6379

# postgres 配置 (pass从env中获取pass这个配置为密码，如果未配置则为空)
postgres:
  host: 127.0.0.1
  port: 5432
  user: vicanso 
  dbname: forest
  password: 123456
  sslmode: disable

# influxdb 配置
influxdb:
  uri: http://127.0.0.1:9999
  bucket: forest
  org: bigtree
  token: YecVRjkFWQHQCq-Qs9NH7XZy8ApyAp9QfwVjqwQC_8bWmjsYRAfYTNveCswl1NPHS8reFoXELQBWKO27maa9tw==
  batchSize: 100

# session的相关配置
session:
  path: /
  key: forest
  ttl: 24h

# key for sign cookie
keys:
  - cuttlefish
  - secret

location:
  baseURL: https://ip.aslant.site/

# router limit
routerLimit:
  # 限制路由访问并发数
  GET /users/v1/me/login: 50

# mail相关配置
mail:
  host: smtp.office365.com
  port: 587
  user: tree.xie@outlook.com
  password: EMAIL_PASS

# 告警接收邮件列表
alarm:
  receiver:
  - tree.xie@outlook.com
