# 系统基本配置
basic:
  name: forest
  # 系统并发限制
  requestLimit: 1000
  listen: :7001

# 用户session的配置
session:
  path: /
  key: forest
  ttl: 240h
  # 用于加密session cookie 
  keys:
  - cuttlefish
  - secret
  trackKey: jt

# redis 配置
redis:
  # 可以配置为下面的形式，则从env中获取REDIS_URI对应的字符串来当redis连接串
  # uri: REDIS_URI
  # uri: redis://:pass@127.0.0.1:6379/?db=0&slow=200ms&maxProcessing=1000
  uri: redis://127.0.0.1:6379/?db=0&slow=200ms&maxProcessing=1000

# postgres postgres配置
postgres:
  uri: postgresql://vicanso:A123456@127.0.0.1:5432/forest

# influxdb 配置
influxdb:
  uri: http://127.0.0.1:9999
  bucket: forest 
  org: bigTree
  token: vEne4wbhYbMOxU6rO2LhIp5ImN5Hah0GA5U35wP-Lq-xMVURCV0NUlVre1g_zLbiSI7JCRM1mRtULGdo4jL1oA==
  batchSize: 100
  flushInterval: 10s
  disabled: false 

# mail相关配置
mail:
  host: smtp.office365.com
  port: 587
  user: tree.xie@outlook.com
  password: EMAIL_PASS

# 告警接收邮件列表
alarm:
  receivers:
  - tree.xie@outlook.com
